name: Layer2 Feature Optimization

on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.py'
      - 'optuna_system/**'
      - 'config/**'
      - 'run_feature_optimization.py'
      - '!**/*.md'

concurrency:
  group: layer2-optimization
  cancel-in-progress: false

jobs:
  layer2:
    name: Run Layer2 Optimization
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip wheel

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Show environment
        run: |
          python -V
          pip -V
          pip list --format=columns | sort

      - name: Run Layer2 feature optimization
        env:
          PYTHONUTF8: '1'
          PYTHONIOENCODING: 'utf-8'
          ENVIRONMENT: 'dev'
        run: |
          python run_feature_optimization.py


