name: Layer2 Feature Optimization

on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.py'
      - 'optuna_system/**'
      - 'config/**'
      - 'run_feature_optimization.py'
      - '!**/*.md'

concurrency:
  group: layer2-optimization
  cancel-in-progress: false

jobs:
  layer2:
    name: Run Layer2 Optimization
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip wheel

      - name: Install minimal dependencies for Layer2
        run: |
          pip install --upgrade pip wheel
          pip install pandas numpy scipy scikit-learn optuna joblib pyyaml python-dotenv requests
          # 可選: 若使用特定特徵工程需附加套件，請於此處補充

      - name: Show environment
        run: |
          python -V
          pip -V
          pip list --format=columns | sort

      - name: Run Layer2 feature optimization
        env:
          PYTHONUTF8: '1'
          PYTHONIOENCODING: 'utf-8'
          ENVIRONMENT: 'dev'
        run: |
          python run_feature_optimization.py


