name: Run Core Layers Optimization

on:
  workflow_dispatch:
    inputs:
      python-version:
        description: "Python version"
        default: "3.9"
        required: false

jobs:
  run-core-layers:
    name: Execute run_core_layers_only.py
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ github.event.inputs.python-version || '3.9' }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run core layers pipeline
        env:
          PYTHONUTF8: "1"
          PYTHONIOENCODING: "utf-8"
          L1_TRIALS: "150"
          L2_TRIALS: "250"
        run: |
          python run_core_layers_only.py

      - name: Upload logs (if present)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: core-layer-logs
          path: |
            logs/
            *.log
          if-no-files-found: ignore

